### ISSUE TITLE
How can I apply the 'pongo_changes.diff' patch?

### ISSUE THREAD

**Issue by ExeRhythm** [pixelomer/PongoBRIX#1]
Hey, awesome project! I have one question, how do I apply the 'pongo_changes.diff' patch? I don't understand the instructions...

**Comment by pixelomer** [comment]
I should have made that clearer. I don't remember if there is a command for this right now but you can manually add the changes to `../pongoOS/src/kernel/modload.c`. Add

    #include <stdlib.h>

at the top of the file and add

    EXPORT_SYMBOL(rand),
    EXPORT_SYMBOL(srand),

to the exports array.

**Comment by pixelomer** [comment]
[See the updated patching step.](https://github.com/pixelomer/PongoBRIX/blob/main/README.md#before-your-begin)
