### ISSUE TITLE
Missing files??

### ISSUE THREAD

**Issue by TrixRebus** [pixelomer/PongoBRIX#11]
when i try to apply the patch I get this error:    src/dynamic/modload.c: No such file or directory

**Comment by legendary-cookie** [comment]
Are you in the pongoOS directory? (Or whatever dir you cloned pongoOS to)

**Comment by TrixRebus** [comment]
yeah

**Comment by TrixRebus** [comment]
![Screen Shot 2021-06-02 at 13 10 56](https://user-images.githubusercontent.com/50786154/120545884-0cb25a00-c3a4-11eb-8f3c-3cde763d6ad7.png)

**Comment by pixelomer** [comment]
You are in the PongoBRIX directory, not the pongoOS directory. Additionally, I think you are using the "Download ZIP" button to download repositories. That's fine for PongoBRIX but you have to use `git clone --recursive` to clone pongoOS.

**Comment by TrixRebus** [comment]
nope, still that error, i must be dumber than i thought lol

**Comment by TrixRebus** [comment]
![image](https://user-images.githubusercontent.com/50786154/120551617-17242200-c3ab-11eb-8645-e844845d3135.png)

**Comment by pixelomer** [comment]
You just renamed the PongoBRIX folder to PongoOS. You are supposed to clone the pongoOS code to `../pongoOS` and the PongoBRIX folder needs to be named something other than pongoOS.

    git clone --recursive https://github.com/checkra1n/pongoOS ../pongoOS

**Comment by TrixRebus** [comment]
thats what i did lmao

**Comment by TrixRebus** [comment]
i was missing some dependancies

**Comment by TrixRebus** [comment]
lol ok, nope, im still lost, i dont think im in the right places. if you are ok to help, I can give you my discord (or here), else no worries

**Comment by TrixRebus** [comment]
i will say kudos to you, this looks like it was hard to make, so well done

**Comment by pixelomer** [comment]
1) Make sure you are in a writable directory (for example `~/Downloads`)
2) Clone pongoOS and PongoBRIX.  
    $ git clone --recursive https://github.com/checkra1n/pongoOS
    $ git clone --recursive https://github.com/pixelomer/PongoBRIX
3) Apply the pongoOS patches.  
    $ cd pongoOS
    $ git apply ../PongoBRIX/pongo_changes.patch
4) Compile pongoOS.  
    $ make
    $ cd scripts
    $ make
5) Boot pongoOS.  
    $ cd ..
    $ /Applications/checkra1n.app/Contents/MacOS/checkra1n -k build/Pongo.bin -p
6) Compile and run PongoBRIX.  
    $ cd ../PongoBRIX
    $ make load_brix
    pongoOS> brix

**Comment by TrixRebus** [comment]
everything work, i can load pongoOS, but then when i run make load_brix i get this
![Screen Shot 2021-06-03 at 11 40 33](https://user-images.githubusercontent.com/50786154/120695772-9de70680-c460-11eb-955a-551a601abe0f.png)

**Comment by pixelomer** [comment]
Make sure you installed `pyusb` and `libusb`.

**Comment by TrixRebus** [comment]
haha, yep thanks, i was just coming to say that lmao. man, you are a f-ing legend, this is so dope lol. here's a follow for ya
