### ISSUE TITLE
Buttonhelper for other processors

### ISSUE THREAD

**Issue by legendary-cookie** [pixelomer/PongoBRIX#12]
Hello. I'm currently trying to get buttonhelper working on an iPhone10,6. May I ask, how do you know where to find the addresses/ Where to scan for them? How would I add support for A11? Would really be helpful if you could tell me how you found those things :D

**Comment by pixelomer** [comment]
This is most likely possible but I don't know how to find the address range myself. The currently scanned address range (`0x20f100000 ... 0x20f101000`) wasn't found by me. A pull request would be appreciated if someone with more low-level experience knows how to find these addresses.

**Comment by legendary-cookie** [comment]
I'll try and see... maybe I can find something. And a small note: buttonhelper panics Pongo right now on A11.

**Comment by legendary-cookie** [comment]
Nice! Thanks for the fix!
