### ISSUE TITLE
compiling on linux?

### ISSUE THREAD

**Issue by Ryan222222** [pixelomer/PongoBRIX#2]
how do i compile this on linux? i do not have any mac hardware and i really want to try this out

**Comment by teelekkung** [comment]
compile pongoOS first (tutorials are in pongoOS github) and don't forget to install this "sudo pip3 install pyusb libusb" after that 
[Makefile.txt](https://github.com/pixelomer/PongoBRIX/files/6523754/Makefile.txt)
i make a custom makefile ,don't know if it gonna work but if not copy the command in makefile and run it manual (I think xcrun and a lot of thing might not present in your linux because it is required iphone sdk and a lot of xcode things ,if you wanna try it out "pip3 install xcrun" (I don't use linux I don't know if it gonna work)(fun fact linux is unix base(or clone if you would)) )

**Comment by pixelomer** [comment]
> compile pongoOS first (tutorials are in pongoOS github) and don't forget to install this "sudo pip3 install pyusb libusb" after that
> [Makefile.txt](https://github.com/pixelomer/PongoBRIX/files/6523754/Makefile.txt)
> i make a custom makefile ,don't know if it gonna work but if not copy the command in makefile and run it manual (I think xcrun and a lot of thing might not present in your linux because it is required iphone sdk and a lot of xcode things ,if you wanna try it out "pip3 install xcrun" (I don't use linux I don't know if it gonna work)(fun fact linux is unix base(or clone if you would)and macOS is unix base toooooo) )

You can't just install `xcrun` on Linux with `pip`. You have to modify the Makefile to make compilation on Linux possible. [pongoOS's README file](https://github.com/checkra1n/pongoOS#building-on-linux) might be helpful.

**Comment by teelekkung** [comment]
Yea that what I wanna type. Thank for add more information

**Comment by Ryan222222** [comment]
now i get this error 

clang: warning: argument unused during compilation: '-arch arm64' [-Wunused-command-line-argument]
In file included from main.c:4:
./pongo.h:27:10: fatal error: 'mach-o/loader.h' file not found
#include <mach-o/loader.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.

**Comment by tak2hu** [comment]
Hi did you solve this?

I was able to get the mach-o/loader.h from pongo os and also theos but I got these errors

```
./pongo.h:162:13: error: conflicting types for 'panic'
extern void panic(const char* string);
            ^
/home/kys/theos/sdks/iPhoneOS14.5.sdk/usr/include/mach/mach.h:86:33: note: previous declaration is here
extern void                     panic(const char *, ...);
                                ^
In file included from button_helper.c:9:
./pongo.h:165:13: error: conflicting types for 'usleep'
extern void usleep(uint32_t usec);
            ^
/home/kys/theos/sdks/iPhoneOS14.5.sdk/usr/include/unistd.h:601:6: note: previous declaration is here
int      usleep(useconds_t) __DARWIN_ALIAS_C(usleep);
         ^
In file included from button_helper.c:9:
./pongo.h:166:13: error: conflicting types for 'sleep'
extern void sleep(uint32_t sec);
            ^
/home/kys/theos/sdks/iPhoneOS14.5.sdk/usr/include/unistd.h:481:3: note: previous declaration is here
         sleep(unsigned int) __DARWIN_ALIAS_C(sleep);
         ^
button_helper.c:53:12: error: incompatible integer to pointer conversion assigning to 'volatile uint32_t *' (aka 'volatile unsigned int *') from 'unsigned long long' [-Werror,-Wint-conversion]
        gpio_base = dt_get_u32_prop("gpio", "reg") + gIOBase;
                  ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
button_helper.c:54:34: error: format specifies type 'unsigned long long' but the argument has type 'volatile uint32_t *' (aka 'volatile unsigned int *') [-Werror,-Wformat]
        printf("gpio_base: 0x%llx\n\n", gpio_base);
```
