### ISSUE TITLE
compile brix error 

### ISSUE THREAD

**Issue by teelekkung** [pixelomer/PongoBRIX#4]
[log.txt](https://github.com/pixelomer/PongoBRIX/files/6523200/log.txt)
here are my log 
try reinstall libusb python and try recompile pongoos non of them work 
only thing change in makefile is python3.8 to python3.9

**Comment by teelekkung** [comment]
so i go to see close issue and find a way to apply patch properly , I will go and test it

**Comment by teelekkung** [comment]
command i use is "patch -p1 < pongo_changes.diff"

**Comment by pixelomer** [comment]
[See the updated patching step.](..#before-your-begin)
