### ISSUE TITLE
How to Apply the small patch in pongo_changes.diff to pongoOS?

### ISSUE THREAD

**Issue by cuj** [pixelomer/PongoBRIX#5]
Hi, I was trying to run pongo brix in my phone, however I have trouble knowing what does this mean:
"Apply the small patch in pongo_changes.diff to ../pongoOS. This patch makes pongoOS export two additional symbols that are required by the CHIP-8 emulator."
So can anyone please tell me how to do that? Thanks.

**Comment by pixelomer** [comment]
See #1.
