### ISSUE TITLE
can't run make load_brix

### ISSUE THREAD

**Issue by project11x** [pixelomer/PongoBRIX#8]
this happens when i enter it
➜  PongoBRIX git:(main) make load_brix
python3.8 ../pongoOS/scripts/upload_data.py brix.bin
Traceback (most recent call last):
  File "../pongoOS/scripts/upload_data.py", line 27, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'
make: *** [load_brix] Error 1

**Comment by pixelomer** [comment]
Make sure you installed pyusb.
```
python3.8 -m pip install pyusb
```
Additionally, you might need to install libusb.
```
# MacPorts
sudo port install libusb

# Homebrew
brew install libusb
```

**Comment by project11x** [comment]
<img width="479" alt="Screenshot 2021-05-22 at 09 38 14" src="https://user-images.githubusercontent.com/48446774/119218601-79467280-bae1-11eb-80b9-3f4140aa4505.png">

**Comment by pixelomer** [comment]
You're probably using the pongoOS build that comes with checkra1n. You need to clone the latest pongoOS code, build it with some changes and use that. See ["Before you begin" in the README](https://github.com/pixelomer/PongoBRIX#before-your-begin).

**Comment by project11x** [comment]
so how do i run this command: 
Boot into pongoOS with checkrain -k ../pongoOS/build/Pongo.bin -p if your device isn't already in pongoOS.

**Comment by project11x** [comment]
or what did i wrong

**Comment by project11x** [comment]
tbh i dont know what to do

**Comment by pixelomer** [comment]
```
/Applications/checkra1n.app/Contents/MacOS/checkra1n -k ../pongoOS/build/Pongo.bin -p
```

**Comment by project11x** [comment]
this happens
<img width="400" alt="Screenshot 2021-05-22 at 11 36 17" src="https://user-images.githubusercontent.com/48446774/119221904-ed891200-baf1-11eb-81d7-84a46abc9a29.png">

**Comment by project11x** [comment]
*when i type 'make load_brix'

**Comment by pixelomer** [comment]
You are definitely not following the steps in the README. `_gFramebuffer` is exported by the latest pongoOS code on GitHub even without modifications.

**Comment by project11x** [comment]
i get ponoOS from here right?:
https://github.com/checkra1n/pongoOS

**Comment by project11x** [comment]
nevermind thx for helping out

great idea i don't know what the fk i did there
